### ISSUE TITLE
設定画面でユーザーIDに使用出来ない記号を入力してフォームを送信すると500が返ってくる

### ISSUE THREAD

**Issue by fumiharun11** [TAK848/pg-backend-final-tatter#4]
## 詳細
以下の手順でプロフィールの設定変更を試みると、エラー画面に遷移してしまう。
今回のケースの場合、フォームの検証エラーとして処理を返すことが適切かと思われるので修正を検討していただきたい。

## 再現手順
検証ユーザーID: miharun

1. 設定画面でユーザーIDを`miharun+`と入力後、パスワードを入力して送信。
![127 0 0 1_8000_mypage_edit_](https://user-images.githubusercontent.com/28529274/141063149-f6b08c73-90d2-4691-b382-fb8d40ee01f0.png)

2. エラー画面に遷移する。
<img width="1658" alt="スクリーンショット 2021-11-10 15 43 57" src="https://user-images.githubusercontent.com/28529274/141063279-0e51ba0c-67cb-490d-a277-47757be2033b.png">
)

**Comment by tak848** [comment]
同様の条件で再現できました。修正次第PRを出します，よろしくお願いします。

**Comment by tak848** [comment]
修正しました！
#6
